### ISSUE TITLE
Click to Browse option?

### ISSUE THREAD

**Issue by krahamath** [gsuitedevs/drive-utils#6]
Hi,

Possible to add click to open a browse window? with Drag and drop

**Comment by krahamath** [comment]
At lease any idea to make that please

**Comment by krahamath** [comment]
Still no response :(

**Comment by femiadeyemi** [comment]
Use stackoverflow.com for asking questions, you will have a better chance of getting it answer there. Anyway, your question is not clean. Please rephrase.
