### ISSUE TITLE
Replace a file's contents

### ISSUE THREAD

**Issue by DataGrump** [gsuitedevs/drive-utils#8]
I provide fileId to MediaUploader's constructor in order to replace an existing file's contents instead of creating a new file. I receive a 404 (Not Found) error.

**Comment by DataGrump** [comment]
OK so here's your problem:

In the MediaUploader constructor, change this line:
**this.httpMethod = options.fileId ? 'PUT' : 'POST';**
to:
this.httpMethod = options.fileId ? 'PATCH' : 'POST';

**Comment by grant** [comment]
Thanks. Fixed with https://github.com/gsuitedevs/drive-utils/commit/3ae5be7194b63f3f9bab042aae0d6600623d3e97.
