### ISSUE TITLE
forked as "UploaderForGoogleDrive.js" for v3 and autoextracting access_token from gapi

### ISSUE THREAD

**Issue by DrPaulBrewer** [gsuitedevs/drive-utils#9]
Thanks for writing upload.js

I've forked it to [this gist](https://gist.github.com/DrPaulBrewer/eaea4ad927389643e56ce566d4ed513e) with some changes that might be useful if someone is interested in taking a look
at cherry picking what should go back in the main branch.

Changes: 

1. use Google Drive API V3 instead of V2

2. wrap code in a "use strict" IIFE, only exposing MediaUploader

3. explicitly export MediaUploader as window.UploaderForGoogleDrive

A name change to `UploaderForGoogleDrive` requires changing your README docs, but avoids
confusion as follows:

[Google's public guide to Drive API](https://developers.google.com/drive/v3/web/about-sdk) mentions a ["simple upload"](https://developers.google.com/drive/v3/web/simple-upload) that is set with a "media" tag and called media upload by some people.  Alternatively there is also a ["resumable upload"](https://developers.google.com/drive/v3/web/resumable-upload) a different procedures, with different calls.  The name change makes it less confusing that this code implements "resumable upload".

Similarly the "ForGoogleDrive" in the name is to play nice with devs who are trying to make their app compatible with multiple services.  

4. if options.token undefined, get access token from [existing window.gapi instance](https://developers.google.com/api-client-library/javascript/reference/referencedocs) that would typically be loaded to access [Google APIs from browser Javascript](https://developers.google.com/api-client-library/javascript/).  If neither an explicit token is passed nor a gapi token can be found, it throws an appropriate error.

add promise wrapper

**Comment by grant** [comment]
PRs are welcome.
This issue doesn't state a specific problem with this sample. As such, I'll close this issue.
